name: dojah_kyc
description: Unofficial Dojah KYC widget
version: 0.1.0+2
homepage: https://github.com/mubharaq/dojah_kyc


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  connectivity_plus: ^5.0.1
  flutter_inappwebview: ^5.8.0
  permission_handler: ^11.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
