name: dojah_kyc
description: Unofficial Dojah KYC widget
version: 0.4.1
homepage: https://github.com/mubharaq/dojah_kyc


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  connectivity_plus: ^6.1.4
  flutter_inappwebview: ^6.1.5
  permission_handler: ^12.0.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

